# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 12:53
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Project name')),
                ('description', models.TextField(null=True, verbose_name='Project description')),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Release date')),
                ('commit_id', models.CharField(max_length=64, null=True, verbose_name='Commit id')),
                ('commit_description', models.TextField(null=True, verbose_name='Commit description')),
                ('description', models.TextField(null=True, verbose_name='Release description')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('ERROR', 'Error'), ('DEPLOYING', 'deploying')], max_length=20, verbose_name='Release status')),
                ('project', models.ForeignKey(on_delete=core.models.Project, to='core.Project')),
            ],
        ),
    ]
